name: Basic CI pipeline

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      
      # goal is to use the already existing mvn wrapper
      # but for better debugging with act locally mvn is installed manually in the pipeline
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Install Z3 Solver
        run: |
          sudo apt-get update
          sudo apt-get install -y z3
          z3 --version

      - name: Upload workspace
        uses: actions/upload-artifact@v4
        with: 
          name: workspace
          path: .
          retention-days: 1

  fetch-remote-test-data:
      runs-on: ubuntu-latest
      needs: setup
      steps:

      - name: Download CSV files from external repo
        run: |
          git clone --depth 1 https://github.com/transforming-variability-artifacts/DOPLER-models external-csv
          rm -rf modelEval
          mkdir -p modelEval
          cp -v external-csv/CSVModels/*.csv modelEval/

      - name: Upload workspace (updated with CSVs)
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: .
          retention-days: 1

  build-and-verify: 
      runs-on: ubuntu-latest
      needs: fetch-remote-test-data
      steps:

      - name: Build & Generate Reports
        run: mvn clean verify site -fn

      - name: Upload workspace (updated with CSVs)
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: .
          retention-days: 1

  

  report:
    runs-on: ubuntu-latest
    needs: build-and-verify
    if: always()
    
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: target/site/surefire-report.html

      - name: Upload checkstyle report
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: target/site/checkstyle.html
