name: Basic CI pipeline

on:
  push:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

  workflow_dispatch:

jobs:

  fetch-remote-test-data:
    runs-on: ubuntu-latest
    steps:
      - name: Download CSV files from external repo
        run: |
          git clone --depth 1 https://github.com/transforming-variability-artifacts/DOPLER-models external-csv
          mkdir -p modelEval
          cp -v external-csv/CSVModels/*.csv modelEval/

      - name: Upload CSV Data
        uses: actions/upload-artifact@v4
        with:
          name: csv-models
          path: modelEval/
          retention-days: 1

  
  build-and-verify:
    runs-on: ubuntu-latest
    needs: fetch-remote-test-data
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download CSV Data
        uses: actions/download-artifact@v4
        with:
          name: csv-models
          path: modelEval/

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Install Z3 Solver
        run: |
          sudo apt-get update
          sudo apt-get install -y z3
          z3 --version

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build & Generate Reports
        # Hier nutzen wir jetzt ./mvnw
        run: ./mvnw clean verify site -fn -B

      - name: Upload Test Report
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: target/site/surefire-report.html

      - name: Upload Checkstyle Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: target/site/checkstyle.html
